kind: Deployment
apiVersion: apps/v1
metadata:
  name: configdeploy
spec:
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: configcontainer
        image: valeryvalavitski/config:1.0
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: https://github.com/cmu nknown/spring-cloud-config-server
---
apiVersion: v1
kind: Service
metadata:
  name: configservice
  labels:
    app: config
spec:
  ports:
  - name: client
    port: 8888
    protocol: TCP
  selector:
    app: config
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
      targetPort: 9092
      nodePort: 32485
  selector:
    app: kafka
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://:9093,OUTSIDE://192.168.49.2:32485 # OUTSIDE = [clusterIp]:[kafka-server port]
            - name: KAFKA_LISTENERS
              value: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            # - name: KAFKA_BROKER_ID # = producer.id в пропертях
            #   value: "1"
            # - name: KAFKA_CREATE_TOPICS # = @KafkaListener в Consumer
            #   value: restTemplateServer
            # - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            #   value: "1"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: producerdeploy
spec:
  selector:
    matchLabels:
        app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer-container
        image: valeryvalavitski/kafkaproducer:2.2
        ports:
        - containerPort: 8080

        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://configservice:8888
---
apiVersion: v1
kind: Service
metadata:
  name: producerservice
  labels:
    app: producer
spec:
  ports:
  - name: client
    port: 8080
    protocol: TCP
  selector:
    app: producer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafkaconsumerdeploy
spec:
  selector:
    matchLabels:
        app: kafkaconsumer
  template:
    metadata:
      labels:
        app: kafkaconsumer
    spec:
      containers:
      - name: kafkaconsumer-container
        image: valeryvalavitski/kafkaconsumer:bbdasads
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://configservice:8888
---
apiVersion: v1
kind: Service
metadata:
  name: consumerservice
  labels:
    app: kafkaconsumer
spec:
  ports:
  - name: client
    port: 8086
    protocol: TCP
  selector:
    app: kafkaconsumer

# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: ibmserver
# spec:
#   selector:
#     matchLabels:
#       app: ibmserver
#   template:
#     metadata:
#       labels:
#         app: ibmserver
#     spec:
#       containers:
#       - name: ibmcontainer
#         image: ibmcom/mq:latest
#         ports:
#         - containerPort: 1414
#         - containerPort: 9443
#         env:
#         - name: LICENSE
#           value: accept
# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: ibmdeployment
# spec:
#   selector:
#     matchLabels:
#         app: ibm
#   template:
#     metadata:
#       labels:
#         app: ibm
#     spec:
#       containers:
#       - name: ibmproducer
#         image: valeryvalavitski/ibmproducer:8050
#         env:
#         - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
#           value: 192.168.49.2:32486
#         - name: LICENSE
#           value: accept
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ibmdeaservice
#   labels:
#     app: ibmdea
# spec:
#   ports:
#   - name: client
#     port: 9000
#     protocol: TCP
#   selector:
#     app: ibmdea
